package com.csidigital.rh.shared.enumeration;

public enum LanguageLevel {
    BEGINNER_A1,BEGINNER,ELEMENTARY_A2,BASIC,INTERMEDIATE_B1,INTERMEDIATE,UPPER_INTERMEDIATE_B2,PROFESSIONAL,ADVANCED_C1,
    FLUENT,PROFICIENT_C2,NATIVE_LANGUAGE,BILINGUAL

}
