package com.csidigital.rh.shared.enumeration;

public enum Title {
    FRONT_END_DEVELOPER, BACK_END_DEVELOPER, FULLSTACK_DEVELOPER, CRM, HUMAN_RESOURCE_MANAGER, HUMAN_RESOURCE,
    PROJECT_MANAGER, TECH_LEAD, UI_UX_DESIGNER, QA_ENGINEER, DEVOPS_ENGINEER, WEB_DEVELOPER,
    OFFICE_MANAGER, ACCOUNTANT, SALES_REPRESENTATIVE, CUSTOMER_SUPPORT_SPECIALIST, MARKETING_COORDINATOR
}
